### ISSUE TITLE
Query string missing when using replaceHash: true

### ISSUE THREAD

**Issue by zeoa-42** [smastrom/vue-use-active-scroll#4]
Hi, 
When using replaceHash: true in my project, I expect the URL's query string to be preserved.

1. I visit the URL: https://vue-use-active-scroll.netlify.app?id=123.
2. After the page loads, The URL becomes https://vue-use-active-scroll.netlify.app, and the query string ?id=123 is missing.

Expected Behavior:
The query string should be preserved in the URL when using replaceHash: true, and it should not be lost during page scrolling.

**Comment by smastrom** [comment]
You're totally right, this is definitely something I missed.

I will release a fix in the next minor. However, since I already have updated the branch I'm working on locally, in the meanwhile, you can use the same code I will release and disable `replaceHash`, so that the "current" watcher is not run in `useActive`.

```vue
<script setup>
import { watch } from 'vue'

const { activeId, activeIndex } = useActive(targets, {
  replaceHash: false
})

watch(activeId, (newId) => {
     // If you have `jumpToFirst` enabled (default), set 0, otherwise -1:
     const start = 0 // or -1
     const baseUrl = window.location.href.split('#')[0]
     const newHash = activeIndex.value > start ? `#${newId}` : ''

     history.replaceState(history.state, '', `${baseUrl}${newHash}`)
})
</script>
```

**Comment by smastrom** [comment]
You're totally right, this is definitely something I missed.

I will release a fix in the next minor. In the meanwhile, you can replicate the hash-update feature by using the same code I will release and temporarly disable `replaceHash`, so that the current (bugged) watcher is not run in `useActive`.

```vue
<script setup>
import { watch } from 'vue'

const { activeId, activeIndex } = useActive(targets, {
  replaceHash: false
})

watch(activeId, (newId) => {
     // If you have 'jumpToFirst' enabled (default), set 0, otherwise -1:
     const start = 0 // or -1
     const baseUrl = window.location.href.split('#')[0]
     const newHash = activeIndex.value > start ? `#${newId}` : ''

     history.replaceState(history.state, '', `${baseUrl}${newHash}`)
})
</script>
```

**Comment by smastrom** [comment]
You're totally right, this is definitely something I missed.

I will release a fix in the next minor. In the meanwhile, you can replicate the fixed hash-update feature by using the same code I will release and temporarly disable `replaceHash`, so that the current (bugged) watcher is not run in `useActive`.

```vue
<script setup>
import { watch } from 'vue'

const { activeId, activeIndex } = useActive(targets, {
  replaceHash: false
})

watch(activeId, (newId) => {
     // If you have 'jumpToFirst' enabled (default), set 0, otherwise -1:
     const start = 0 // or -1
     const baseUrl = window.location.href.split('#')[0]
     const newHash = activeIndex.value > start ? `#${newId}` : ''

     history.replaceState(history.state, '', `${baseUrl}${newHash}`)
})
</script>
```

**Comment by zeoa-42** [comment]
@smastrom That's great. Thank you very much!
